Netvent/storyly-sdk

flutter/StorylyDemo/lib/main.dart, flutter/StorylyDemo/lib/scroll_example.dart, flutter/StorylyDemo/pubspec.lock, flutter/StorylyDemo/pubspec.yaml, flutter/storyly_flutter/example/ios/Podfile.lock, flutter/storyly_flutter/example/lib/main.dart, flutter/storyly_flutter/example/pubspec.lock, flutter/storyly_flutter/example/pubspec.yaml, flutter/storyly_flutter/lib/storyly_flutter.dart, flutter/storyly_flutter/pubspec.lock, flutter/storyly_flutter/pubspec.yaml
Null safety migration done by migration tool.
Note:
Storyly Demo Storyly dependency needs to be updated after storyly new version released.
=> Flutter Null Safety Migration

flutter/storyly_flutter/android/build.gradle, flutter/storyly_flutter/ios/Classes/FlutterStorylyView.swift, flutter/storyly_flutter/ios/Classes/FlutterStorylyViewWrapper.swift, flutter/storyly_flutter/ios/Classes/SwiftStorylyFlutterPlugin.swift, flutter/storyly_flutter/lib/storyly_flutter.dart
=> feat(core-flutter): add view id handling to storyly_flutter for monetization

react-native/storyly-react-native/index.d.ts, react-native/storyly-react-native/ios/STStorylyGroupViewManager.m, react-native/storyly-react-native/ios/STStorylyManager.m, react-native/storyly-react-native/ios/StorylyReactNative-Bridging-Header.h
=> fix(core-rn): fix RCT UIManager header not included

moments/react-native/storyly-moments-react-native/android/src/main/java/com/appsamurai/storyly/moments/reactnative/STStorylyMomentsModule.kt
=> fix(moments-rn-android): fix momentsPayload variable types and values

flutter/storyly_flutter/android/src/main/kotlin/com/appsamurai/storyly/storyly_flutter/FlutterStorylyView.kt, flutter/storyly_flutter/ios/Classes/FlutterStorylyViewWrapper.swift, flutter/storyly_flutter/lib/storyly_flutter.dart
=> fix(storyly-flutter):  add resume-pause-close story APIs

react-native/storyly-react-native/RNStoryly.js, react-native/storyly-react-native/android/src/main/java/com/appsamurai/storyly/reactnative/STStorylyManager.kt, react-native/storyly-react-native/ios/STStorylyManager.m, react-native/storyly-react-native/ios/STStorylyManager.swift, react-native/storyly-react-native/ios/STStorylyView.swift
=> fix(storyly-react-native): add resume-pause-close story APIs

react-native/storyly-react-native/RNStoryly.js, react-native/storyly-react-native/android/src/main/java/com/appsamurai/storyly/reactnative/STStorylyManager.kt, react-native/storyly-react-native/index.d.ts, react-native/storyly-react-native/ios/RCTConvert+Storyly.swift
=> feat(str-rn-product): add locale to product feed

flutter/storyly_flutter/android/src/main/kotlin/com/appsamurai/storyly/storyly_flutter/FlutterStorylyView.kt, flutter/storyly_flutter/ios/Classes/FlutterStorylyViewWrapper.swift, flutter/storyly_flutter/lib/storyly_flutter.dart
=> feat(str-flutter-product): add locale to product feed

react-native/storyly-react-native-legacy/RNStoryly.js, react-native/storyly-react-native-legacy/android/src/main/java/com/appsamurai/storyly/reactnative/STStorylyManager.kt, react-native/storyly-react-native-legacy/ios/STStorylyView.swift
=> fix(str-rn-legacy): fix  storylyConfig update not rendering factory

react-native/storyly-react-native/android/src/main/java/com/appsamurai/storyly/reactnative/STStorylyDataConverter.kt, react-native/storyly-react-native/index.d.ts, react-native/storyly-react-native/ios/RCTConvert+Storyly.swift, react-native/storyly-react-native/ios/STStorylyDataConverter.swift
=> feat(str-rn): implement StoryGroupStyle data converters

react-native/storyly-react-native/android/src/main/java/com/appsamurai/storyly/reactnative/STStorylyManager.kt
remove nullability from addView and removeViewAt of ViewGroupManager's overriden methods
=> bug(storyly-rn): remove nullability from parameters

react-native/storyly-react-native/StorylyDemo/ios/Podfile.lock, react-native/storyly-react-native/android/build.gradle, react-native/storyly-react-native/android/src/main/java/com/appsamurai/storyly/reactnative/STStorylyDataConverter.kt, react-native/storyly-react-native/index.d.ts, react-native/storyly-react-native/ios/STStorylyDataConverter.swift, react-native/storyly-react-native/storyly-react-native.podspec
=> feat(str-rn): add customPayload to StoryComponent and missing layers

flutter/storyly_flutter/android/build.gradle, flutter/storyly_flutter/android/src/main/kotlin/com/appsamurai/storyly/storyly_flutter/FlutterStorylyView.kt, flutter/storyly_flutter/example/ios/Podfile.lock, flutter/storyly_flutter/ios/Classes/FlutterStorylyViewWrapper.swift, flutter/storyly_flutter/ios/storyly_flutter.podspec, flutter/storyly_flutter/lib/storyly_flutter.dart
=> feat(str-flutter): add customPayload to StoryComponent and missing layers

react-native/storyly-react-native/android/src/main/java/com/appsamurai/storyly/reactnative/STStorylyManager.kt
=> feat(str-rn): fix storylySizeChanged event on android

react-native/storyly-react-native/RNVerticalFeed.js, react-native/storyly-react-native/RNVerticalFeedBar.js, react-native/storyly-react-native/RNVerticalFeedPresenter.js, react-native/storyly-react-native/android/src/main/java/com/appsamurai/storyly/reactnative/STStorylyManager.kt, react-native/storyly-react-native/android/src/main/java/com/appsamurai/storyly/reactnative/verticalFeed/STVerticalFeedManager.kt, react-native/storyly-react-native/android/src/main/java/com/appsamurai/storyly/reactnative/verticalFeedBar/STVerticalFeedBarManager.kt, react-native/storyly-react-native/android/src/main/java/com/appsamurai/storyly/reactnative/verticalFeedPresenter/STVerticalFeedPresenterManager.kt, react-native/storyly-react-native/index.d.ts, react-native/storyly-react-native/ios/VerticalFeed/STVerticalFeedManager.m, react-native/storyly-react-native/ios/VerticalFeed/STVerticalFeedManager.swift, react-native/storyly-react-native/ios/VerticalFeed/STVerticalFeedView.swift, react-native/storyly-react-native/ios/VerticalFeedBar/STVerticalFeedBarManager.m, react-native/storyly-react-native/ios/VerticalFeedBar/STVerticalFeedBarManager.swift, react-native/storyly-react-native/ios/VerticalFeedBar/STVerticalFeedBarView.swift, react-native/storyly-react-native/ios/VerticalFeedPresenter/STVerticalFeedPresenterManager.m, react-native/storyly-react-native/ios/VerticalFeedPresenter/STVerticalFeedPresenterView.swift
=> refactor(vf-rn): rename vertical feed open story

react-native/storyly-react-native/android/src/main/java/com/appsamurai/storyly/reactnative/STStorylyDataConverter.kt, react-native/storyly-react-native/android/src/main/java/com/appsamurai/storyly/reactnative/verticalFeedBar/STVerticalFeedDataConverter.kt, react-native/storyly-react-native/index.d.ts, react-native/storyly-react-native/ios/STStorylyDataConverter.swift, react-native/storyly-react-native/ios/VerticalFeedBar/STVerticalFeedDataConverter.swift
=> feat(str-rn): add StoryImageQuizComponent for rn

flutter/storyly_flutter/android/src/main/kotlin/com/appsamurai/storyly/storyly_flutter/StorylyData.kt, flutter/storyly_flutter/android/src/main/kotlin/com/appsamurai/storyly/storyly_flutter/vertical_feed/VerticalFeedData.kt, flutter/storyly_flutter/ios/Classes/StorylyData.swift, flutter/storyly_flutter/ios/Classes/VerticalFeedData.swift, flutter/storyly_flutter/lib/storyly_flutter.dart, flutter/storyly_flutter/lib/vertical_feed_data.dart
=> feat(str-flutter): add StoryImageQuizComponent for flutter

react-native/storyly-react-native/android/src/main/java/com/appsamurai/storyly/reactnative/STStorylyManager.kt, react-native/storyly-react-native/android/src/main/java/com/appsamurai/storyly/reactnative/verticalFeed/STVerticalFeedManager.kt, react-native/storyly-react-native/android/src/main/java/com/appsamurai/storyly/reactnative/verticalFeedBar/STVerticalFeedBarManager.kt, react-native/storyly-react-native/android/src/main/java/com/appsamurai/storyly/reactnative/verticalFeedPresenter/STVerticalFeedPresenterManager.kt
=> fix(str-rn): fix nullable string cast issue for RN 0.79

react-native/storyly-react-native-fabric/android/src/main/java/com/storylyreactnative/data/StorylyBundle.kt, react-native/storyly-react-native-fabric/example/android/app/src/main/AndroidManifest.xml, react-native/storyly-react-native-fabric/ios/StorylyBundle.swift, react-native/storyly-react-native-fabric/src/StorylyGroupViewFactory.tsx, react-native/storyly-react-native-fabric/src/data/util.ts
=> fix(str-rn-fabric): fix android size resolve and rtl not rendering groups

react-native/storyly-react-native-fabric/ios/STStoryGroupViewFactory.swift, react-native/storyly-react-native-fabric/ios/STStorylyView.swift, react-native/storyly-react-native-fabric/ios/StorylyReactNativeView.mm
=> fix(str-rn-fabric): fix custom group  unmount crash on ios
